server:
  # 端口
  port: 9090

spring:
  config:
    # 导入bootstrap.yml（高版本springboot需要这样才能调用）
    import: classpath:/bootstrap.yml
  application:
    # 应用程序名
    name: hb-gateway
  cloud:
    nacos:
      discovery:
        # nacos注册地址
        server-addr: ${hb.nacos.addr}
        # 命名空间
        namespace: ${hb.nacos.namespace}
    gateway:
      discovery:
        locator:
          #是否启动自动识别nacos服务
          enabled: true
  profiles:
    # 激活开发环境
    active: dev


